version: "3"
services:
  app:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=bcbc
      - POSTGRES_USER=root
      - POSTGRES_DB=academic-portal-db
